# Generated by Django 5.0.6 on 2024-05-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
    ]
